### ISSUE TITLE
Add search exclusions

### ISSUE THREAD

**Issue by geralt** [m3n0sd0n4ld/GooFuzz#1]
Hi @m3n0sd0n4ld,

awesome tool. Have you ever think about including exclusions when searching? When we are analyzing a domain there are many times when it is useful to remove subdomains from the results so that more domains appear with the same search.

This is not an issue, maybe a suggestion.

Regards

------------------

Hola @m3n0sd0n4ld,

muy buena herramienta. ¿Has considerado incluir la exclusiones a la hora de buscar?  Cuando estamos examinando un dominio hay veces que es útil quitar subdominios de los resultados para que con la misma búsqueda vayan apareciendo más dominios (sin tener que aumentar el número de páginas a tener en cuenta).

Este comentario no es tanto un problema como una sugerencia.

Un saludo.

**Comment by m3n0sd0n4ld** [comment]
Hi @geralt!

Thanks for bothering to use the tool and for investing your time in proposing new features. I found your proposal interesting, so I'm going to write it down in the list of improvements to work on it and try to make it available in the next version.

Thank you very much, best regards!

---

Hola  #@geralt!

Gracias por molestarte en utilizar la herramienta y por invertir tu tiempo en proponer nuevas funcionalidades. Me ha parecido interesante tu propuesta, así que me lo voy anotar en la lista de mejoras para trabajar en ello e intentar que esté disponible en la próxima versión.

Muchísimas gracias, un saludo!

> Hola @m3n0sd0n4ld,
> 
> herramienta impresionante. ¿Alguna vez has pensado en incluir exclusiones al buscar? Cuando estamos analizando un dominio hay muchas veces en las que es útil eliminar subdominios de los resultados para que aparezcan más dominios con la misma búsqueda.
> 
> Esto no es un problema, tal vez una sugerencia.
> 
> Saludos
> 
> Hola @m3n0sd0n4ld,
> 
> muy buena herramienta. ¿Ha considerado incluir la exclusiones a la hora de buscar? Cuando estamos examinando un dominio hay veces que es útil quitar subdominios de los resultados para que con la misma búsqueda vayan apareciendo más dominios (sin tener que aumentar el número de páginas a tener en cuenta).
> 
> Este comentario no es tanto un problema como una sugerencia.
> 
> Un saludo.

**Comment by m3n0sd0n4ld** [comment]
**GooFuzz v.1.1** version containing this option has been released, thanks for the idea.
