### ISSUE TITLE
[!] Oops... Looks like Google has temporarily blocked your IP address.

### ISSUE THREAD

**Issue by Iamtheoldman** [m3n0sd0n4ld/GooFuzz#10]
(base) dameonjensen@Dameons-Laptop GooFuzz % ./GooFuzz -t Blankforsecurityreasons.com -w wp-admin -p 1

*********************************************************
* GooFuzz 1.2.2 - The Power of Google Dorks		*
*********************************************************

Target: Blank for security reasons 

[!] Oops... Looks like Google has temporarily blocked your IP address.
(base) dameonjensen@Dameons-Laptop GooFuzz %

**Comment by m3n0sd0n4ld** [comment]
Repeated, you need read readme.md file, please: Issue [https://github.com/m3n0sd0n4ld/GooFuzz/issues/2](https://github.com/m3n0sd0n4ld/GooFuzz/issues/2)
