### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by 0xhunster** [m3n0sd0n4ld/GooFuzz#2]
![image](https://user-images.githubusercontent.com/46501627/175818300-6deae325-c13a-4597-a876-8e81ab785a8c.png)

**Comment by m3n0sd0n4ld** [comment]
Hi!

It seems that it is a **problem of your connection or Google has banned your IP temporarily** (as already reported in the Disclaimer of the tool).

![](https://i.postimg.cc/tTyKCf2w/issues-2.png)

![](https://i.postimg.cc/CKfvTN0t/issues-2-2.png)

I also take advantage of the fact that it is not a good idea to use "_-p 10_", this tool (and to avoid Google bans) is to get more results with fewer requests. So I recommend that the more files you try to search, the less pages you search, and that you only use the "_-p_" for specific files (for example, to get all possible pdf).

Thanks for your comment, but this is not a failure of the tool, it is a temporary ban from Google or a problem with your connection.
