### ISSUE TITLE
Showing different results for the same request?

### ISSUE THREAD

**Issue by srand2** [m3n0sd0n4ld/GooFuzz#3]
Hey. First of all awesome project! I'm wondering if google starts blocking the requests after a few attempts? Im suggesting this because Im starting to get no results returned.

**Comment by m3n0sd0n4ld** [comment]
Hey! Thanks for feedback!

You can read this issue at https://github.com/m3n0sd0n4ld/GooFuzz/issues/2

For the next version, I will try to make the message different when Google blocks.

Thanks for your comment

**Comment by m3n0sd0n4ld** [comment]
This has been fixed in version 1.2.
