### ISSUE TITLE
Make sequence for loop more compatible

### ISSUE THREAD

**Issue by IshtarStar** [m3n0sd0n4ld/GooFuzz#5]
https://github.com/m3n0sd0n4ld/GooFuzz/blob/4a17e39628ed8d937579117da8056789c39aa234/GooFuzz#L129

for page in \`seq 0 10 100\`; do

**Comment by m3n0sd0n4ld** [comment]
Hi,

Thanks for your input, but that is already changed in the code for the next version.

Best regards!

**Comment by m3n0sd0n4ld** [comment]
This has been fixed in version 1.2.
