### ISSUE TITLE
-b not working 

### ISSUE THREAD

**Issue by catchmeifyoucaan** [m3n0sd0n4ld/GooFuzz#7]
hello, thank you for this great tool, its one of my workflow tools, but i'm having issue with the -b cookies.txt file, it always return file corrupted or not found:

./GooFuzz -t sidefx.com -e jspa,do,action,jsp,aspx,asp,csv,xsl,xml,config,log,php,txt,json,pem,git,svg,env,svn,zip,bin,dat,db,sql,sav,rss,dll,dmp,msi,ini,tmp,rtf,cgi,mdb,vcf,eml,jar,wsf,sys,cfg,drv,key,htaccess,shtml,conf,ftp,pcf,yaml,old -b cookies.txt
./GooFuzz: line 175: file: command not found

[!] This file is not in text format or is corrupted.

this is my text file format, anything i'm missing?
"c_user=1000777419xxxx;xs=27:wVB4aNzYBHxxxx:2:1670998259:-1:xxxx".

**Comment by m3n0sd0n4ld** [comment]
Hi,

The format is without <"> with a space between c_user=XXX; xs=XXX.

Never publish your ID and cookies, that cookie format "xs" is not functional, go to facebook.com or go directly to developer.facebook.com, you will see that the cookie is longer.

Greetings,

**Comment by catchmeifyoucaan** [comment]
oh thank you, yes the xs is longer, i just corrected that now but i still have the error 
"c_user=1xxxxxxxxxxxxxx419xxxx; xs=27:wxxxxxxxxBHxxxx:2:16xxxxxxxxxxxxxxxxxxxx"
i added the space do you mean i have to add <'> like this
"c_user=<1xxxxxxxxxxxxxx419xxxx>; xs=<27:wxxxxxxxxBHxxxx:2:16xxxxxxxxxxxxxxxxxxxx>"
because either way it still doesmt work for me, thanks

**Comment by m3n0sd0n4ld** [comment]
No, I mean that you don't have to include the double quotes in the cookies.txt file, i.e., you have to put it like this c_user=1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx419xxxxxxxx; xs=27:wxxxxxxxxxxxxxBHxxxx:2:16xxxxxxxxxxxxxxxxxxx

I am going to modify the information exposed in Github, so that there is no error.

Thanks for your feedback!

**Comment by catchmeifyoucaan** [comment]
hello thank you, the -b now accepts my cookies.txt but it wont return anything, its all showing 

Sorry, no results found for jspa.

Sorry, no results found for do.

Sorry, no results found for action.

Sorry, no results found for jsp.

Sorry, no results found for aspx.

Sorry, no results found for asp.

Sorry, no results found for csv.

Sorry, no results found for xsl.

Sorry, no results found for xml.

Sorry, no results found for config.

Sorry, no results found for log.

Sorry, no results found for php.

Sorry, no results found for txt.

Sorry, no results found for json.

Sorry, no results found for pem.

Sorry, no results found for git.

Sorry, no results found for svg.

Sorry, no results found for env.

Sorry, no results found for svn.

Sorry, no results found for zip.

Sorry, no results found for bin.

Sorry, no results found for dat.

Sorry, no results found for db.

Sorry, no results found for sql.

Sorry, no results found for sav.

Sorry, no results found for rss.

Sorry, no results found for dll.

Sorry, no results found for dmp.

Sorry, no results found for msi.

Sorry, no results found for ini.

Sorry, no results found for tmp.

Sorry, no results found for rtf.

Sorry, no results found for cgi.

Sorry, no results found for mdb.

Sorry, no results found for vcf.

Sorry, no results found for eml.

Sorry, no results found for jar.

Sorry, no results found for wsf.

Sorry, no results found for sys.

Sorry, no results found for cfg.

Sorry, no results found for drv.

Sorry, no results found for key.

Sorry, no results found for htaccess.

Sorry, no results found for shtml.

Sorry, no results found for conf.

Sorry, no results found for ftp.

Sorry, no results found for pcf.

Sorry, no results found for yaml.
even on domains that i use it for before and it return results, it doesnt give warning that google block me or anything but no results

**Comment by m3n0sd0n4ld** [comment]
Hi,

Excuse me, I was of vacations.

I see the problem, Facebook to fixed the "vulnerability" :(

Sorry, and thanks for information.

Regards
