### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by dhabierre** [m3n0sd0n4ld/GooFuzz#9]
Hi,

It should be nice to add a `Dockerfile` example to package the binary inside a Docker image (for Windows users for example)

Here an example that works on my Windows 11 computer with Docker Desktop (=> *Linux containers*):

```
FROM alpine:3.18

ARG GOOFUZZ_VERSION=1.2.2

RUN apk --no-cache update && \
    apk --no-cache add bash curl zip

ADD https://github.com/m3n0sd0n4ld/GooFuzz/releases/download/${GOOFUZZ_VERSION}/GooFuzz_release_${GOOFUZZ_VERSION}.zip /tmp

WORKDIR /tmp

RUN unzip /tmp/GooFuzz_release_${GOOFUZZ_VERSION}.zip
RUN chmod +x /tmp/GooFuzz_release_${GOOFUZZ_VERSION}/GooFuzz
RUN mv /tmp/GooFuzz_release_${GOOFUZZ_VERSION}/GooFuzz /usr/local/bin
RUN mv /tmp/GooFuzz_release_${GOOFUZZ_VERSION}/wordlists /usr/local/bin
RUN rm -rf /tmp/*

WORKDIR /

CMD ["/bin/bash"]
```

Command to build the image:

```bash
# go to the folder that contains the Dockerfile

docker build -t goofuzz:1.2.2 .
```

Once the image is built:

```bash
docker images

# Output:
# REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
# goofuzz      1.2.2     5cbc6869778a   11 seconds ago   14.2MB
```

Command to execute the container:

```bash
docker run -it goofuzz:1.2.2
```

Then enter `GooFuzz -h`

Hope this help :)

**Comment by m3n0sd0n4ld** [comment]
Hello!

Sorry for the delay. 

I'm going to try the instructions and if everything works great, I'll post it and mention you, of course.

Thanks for sharing!

**Comment by m3n0sd0n4ld** [comment]
Hi!

I have uploaded a new version, I finally tweaked the Dockerfile to not depend on specifying versions and I have adapted it with the just and necessary.

[https://github.com/m3n0sd0n4ld/GooFuzz/releases/tag/1.2.3](https://github.com/m3n0sd0n4ld/GooFuzz/releases/tag/1.2.3)

Anyway, if you detect any anomaly, please let me know.

Thanks for the idea and your proposal, take care!
